// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmkwrzrcefgoqsgiorek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJta3dyenJjZWZnb3FzZ2lvcmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzMwMzQsImV4cCI6MjA2NDkwOTAzNH0.kV6fKU4XVvnUCXdgKtUusBCnFBEEvyD9BYbjjcZ256U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);